# Generated by Django 3.0.6 on 2020-05-23 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('boardgames', '0001_initial'), ('boardgames', '0002_auto_20200522_0048'), ('boardgames', '0003_auto_20200523_1556'), ('boardgames', '0004_auto_20200523_1706'), ('boardgames', '0005_auto_20200523_1707')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgg_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=256)),
                ('min_players', models.IntegerField(null=True)),
                ('max_players', models.IntegerField(null=True)),
                ('best_with', models.CharField(max_length=4, null=True)),
                ('len_m', models.IntegerField(null=True)),
                ('min_len_m', models.IntegerField(null=True)),
                ('max_len_m', models.IntegerField(null=True)),
                ('average', models.DecimalField(decimal_places=5, max_digits=6, null=True)),
                ('bayes_average', models.DecimalField(decimal_places=5, max_digits=6, null=True)),
                ('weight', models.DecimalField(decimal_places=5, max_digits=6, null=True)),
                ('bgstats_id', models.IntegerField(null=True, unique=True)),
                ('no_points', models.BooleanField(null=True)),
                ('highest_wins', models.BooleanField(null=True)),
                ('cooperative', models.BooleanField(null=True)),
                ('uses_teams', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BoardGameCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='BoardGameMechanic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mechanic_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='BoardGameTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_date', models.DateField(null=True)),
                ('ignore', models.BooleanField(null=True)),
                ('comments', models.CharField(max_length=512, null=True)),
                ('difficulty', models.CharField(max_length=64, null=True)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plays', to='boardgames.BoardGame')),
                ('play_id', models.IntegerField(default=None, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=32, null=True, unique=True)),
                ('bgg_username', models.CharField(max_length=32, null=True)),
                ('bgg_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalBoardGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_tags', models.ManyToManyField(to='boardgames.BoardGameTag')),
            ],
        ),
        migrations.AddField(
            model_name='boardgame',
            name='categories',
            field=models.ManyToManyField(to='boardgames.BoardGameCategory'),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='mechanics',
            field=models.ManyToManyField(to='boardgames.BoardGameMechanic'),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='owners',
            field=models.ManyToManyField(to='boardgames.Player'),
        ),
        migrations.CreateModel(
            name='BoardGameExpansion',
            fields=[
                ('boardgame_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='boardgames.BoardGame')),
                ('base_game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expansions', to='boardgames.BoardGame')),
            ],
            bases=('boardgames.boardgame',),
        ),
        migrations.CreateModel(
            name='PersonalBoardGameExpansion',
            fields=[
                ('boardgameexpansion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='boardgames.BoardGameExpansion')),
                ('expansion_tags', models.ManyToManyField(to='boardgames.BoardGameTag')),
            ],
            bases=('boardgames.boardgameexpansion',),
        ),
        migrations.CreateModel(
            name='PlayerScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, null=True)),
                ('role', models.CharField(max_length=64, null=True)),
                ('start_player', models.BooleanField(default=False)),
                ('seat_order', models.IntegerField(default=0)),
                ('new_player', models.BooleanField(default=False)),
                ('team', models.IntegerField(null=True)),
                ('winner', models.BooleanField(null=True)),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='boardgames.Play')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_score', to='boardgames.Player')),
            ],
        ),
    ]
